chore: lock file problem, lets try a quick fix

diff --git a/projects/trecim-citygml-viewer/Dockerfile.prod b/projects/trecim-citygml-viewer/Dockerfile.prod
--- a/projects/trecim-citygml-viewer/Dockerfile.prod
+++ b/projects/trecim-citygml-viewer/Dockerfile.prod
@@ -11,15 +11,16 @@ WORKDIR /app
 # RUN echo @paramountric:registry=https://npm.pkg.github.com/ >> ~/.npmrc
 # RUN echo //npm.pkg.github.com/:_authToken=$CR_PAT >> ~/.npmrc
 
-# Install dependencies based on the preferred package manager
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+COPY package.json ./
 
-RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+RUN yarn
+
+# RUN \
+#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#   elif [ -f package-lock.json ]; then npm ci; \
+#   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+#   else echo "Lockfile not found." && exit 1; \
+#   fi
 
 # Rebuild the source code only when needed
 FROM node:16-alpine AS builder
